[package]
org = "ballerina"
name = "tool.asyncapi"
version = "0.11.1"
authors = ["Ballerina"]
keywords = ["asyncapi", "asyncapi tool", "event-driven", "websocket", "asyncapi generator"]
license = ["Apache-2.0"]
