[package]
org = "ballerina"
name = "tool.asyncapi"
version = "0.12.1"
authors = ["Ballerina"]
keywords = ["asyncapi", "asyncapi tool", "asyncapi generator", "asyncapi spec"]
license = ["Apache-2.0"]
distribution = "2201.13.0"
