/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'java'
    id 'checkstyle'
}

java {
    modularity.inferModulePath = true
}

compileJava {
    doFirst {
        options.compilerArgs += ['--module-path', classpath.asPath]
        classpath = files()
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.apicurio:apicurio-data-models:2.3.1"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonDataformatYamlVersion}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonDataformatYamlVersion}"
    implementation "org.semver4j:semver4j:${semver4jVersion}"
    implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
    implementation "org.apache.logging.log4j:log4j-api:${log4jVersion}"

    checkstyle project(':checkstyle')
    checkstyle "com.puppycrawl.tools:checkstyle:${checkstylePluginVersion}"
}

checkstyle {
    toolVersion "${checkstylePluginVersion}"
    configFile rootProject.file("config/checkstyle/build/checkstyle.xml")
    configProperties = ["suppressionFile" : file("${rootDir}/config/checkstyle/build/suppressions.xml")]
}

def excludePattern = '**/module-info.java'
tasks.withType(Checkstyle) {
    exclude excludePattern
}

tasks.withType(Checkstyle).configureEach {
    dependsOn(":checkstyle:downloadCheckstyleRuleFiles")
    mustRunAfter(
            ":checkstyle:compileTestJava",
            ":checkstyle:checkstyleMain",
            ":checkstyle:checkstyleTest",
            ":checkstyle:test",
            ":checkstyle:processTestResources"
    )
}

test {
    useTestNG() {
        suites "src/test/resources/testng.xml"
    }
}
