plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "io.apicurio:apicurio-data-models:2.3.1"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonDataformatYamlVersion}"
    implementation "org.semver4j:semver4j:${semver4jVersion}"
    implementation "jakarta.ws.rs:jakarta.ws.rs-api:${jakartaWsRsVersion}"

    checkstyle project(':checkstyle')
    checkstyle "com.puppycrawl.tools:checkstyle:${checkstylePluginVersion}"
}

checkstyle {
    toolVersion "${checkstylePluginVersion}"
    configFile rootProject.file("config/checkstyle/build/checkstyle.xml")
    configProperties = ["suppressionFile" : file("${rootDir}/config/checkstyle/build/suppressions.xml")]
}

def excludePattern = '**/module-info.java'
tasks.withType(Checkstyle) {
    exclude excludePattern
}

checkstyleMain.dependsOn(":checkstyle:downloadCheckstyleRuleFiles")
checkstyleMain.dependsOn(":checkstyle:compileTestJava")
checkstyleMain.dependsOn(":checkstyle:checkstyleMain")
checkstyleMain.dependsOn(":checkstyle:checkstyleTest")
checkstyleMain.dependsOn(":checkstyle:test")
checkstyleMain.dependsOn(":checkstyle:processTestResources")
checkstyleTest.dependsOn(":checkstyle:downloadCheckstyleRuleFiles")
