org.gradle.caching=true
group=io.ballerina
version=0.12.0-SNAPSHOT
artifactId=asyncapi-tool

# Plugin Versions
spotbugsPluginVersion=6.0.18
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.4.0
releasePluginVersion=2.8.0
checkstylePluginVersion=10.12.1
javaModularityPluginVersion=1.7.0
sonarqubePluginVersion=4.0.0.2929
ballerinaGradlePluginVersion=2.3.0

#dependency
ballerinaLangVersion=2201.13.0-20251015-051600-27035519
testngVersion=7.6.1
slf4jVersion=1.7.30
commonsIoVersion=2.11.0
jacksonDataformatYamlVersion=2.15.3
org.gradle.jvmargs=-Xmx4096M
log4jVersion=2.14.1
picocliVersion=4.7.4
apiCurioVersion=2.0.4
javaModularityVersion=1.8.15

# Stdlib Level 01
stdlibIoVersion=1.8.0
stdlibTimeVersion=2.8.0-20251015-144800-cc738de
stdlibUrlVersion=2.6.0
observeVersion=1.5.0

# Stdlib Level 02
stdlibConstraintVersion=1.7.0
stdlibCryptoVersion=2.9.1-20250925-191400-cd7bbcf
stdlibLogVersion=2.13.0
stdlibOsVersion=1.10.0
stdlibTaskVersion=2.11.0
observeInternalVersion=1.5.0
stdlibDataXmldataVersion=1.3.0

# Stdlib Level 03
stdlibCacheVersion=3.10.0
stdlibFileVersion=1.12.0
stdlibMimeVersion=2.12.0
stdlibUuidVersion=1.10.0

# Stdlib Level 04
stdlibAuthVersion=2.14.0
stdlibDataJsonDataVersion=1.1.3
stdlibJwtVersion=2.15.1
stdlibOAuth2Version=2.15.0-20251015-145700-e6cf70e

# Stdlib Level 05
stdlibHttpVersion=2.15.0-20251015-160100-72c02e9

# Stdlib Level 06
stdlibWebsocketVersion=2.15.0-20251015-184000-5d33536

# Ballerinax
stdlibKafkaVersion=4.6.1
stdlibRabbitMqVersion=3.3.0
