/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package io.ballerina.asyncapi.generator.http.generator;

import io.ballerina.asyncapi.generator.GeneratorException;
import io.ballerina.asyncapi.generator.http.model.DispatchTestCase;
import io.ballerina.asyncapi.generator.http.model.WebhookAuthConfig;
import io.ballerina.asyncapi.generator.http.utils.HeaderTemplateParser;
import io.ballerina.asyncapi.generator.http.utils.HeaderTemplateParser.HeaderTemplate;
import io.ballerina.compiler.syntax.tree.SyntaxTree;
import io.ballerina.tools.text.TextDocument;
import io.ballerina.tools.text.TextDocuments;
import org.ballerinalang.formatter.core.Formatter;
import org.ballerinalang.formatter.core.FormatterException;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates {@code tests/dispatch_test.bal}: one real {@code @test:Config} dispatch-verification
 * test per event defined in the spec, plus one stub service implementation per service type
 * covering every one of its remote functions.
 *
 * <p>Each test sends a signed HTTP request built from a same-named JSON fixture (expected at
 * {@code <payloadDir>/<eventIdentifier>.json}, not generated by this class -- fixtures are
 * curated data, not synthesizable from a schema alone) to a listener started on a dedicated test
 * port, then asserts the expected remote function fired.
 *
 * <p>Signing currently supports a single HMAC-SHA256 digest of the raw body, hex-encoded, spliced
 * into the configured {@code headerFormat} (literal prefix/suffix text around a single
 * {@code signature} placeholder, e.g. {@code "sha256=$signature"} -- the scheme GitHub's spec
 * uses). Other algorithms/encodings, and richer {@code headerFormat}s with additional placeholders
 * or {@code $config}/{@code $header} composition, are not yet supported by this generator and are
 * out of scope for this pass.
 */
public class DispatchTestGenerator {

    private static final String DEFAULT_PAYLOAD_DIR = "tests/resources/trigger_payloads";
    private static final int TEST_PORT = 9091;
    private static final String TEST_SECRET = "trigger-test-secret";

    private final List<DispatchTestCase> testCases;
    private final WebhookAuthConfig webhookAuthConfig;

    /**
     * Creates a generator for the given dispatch test cases and webhook auth configuration.
     *
     * @param testCases         the extracted dispatch test cases, one per event
     * @param webhookAuthConfig the webhook authentication configuration (header name, algorithm)
     */
    public DispatchTestGenerator(List<DispatchTestCase> testCases, WebhookAuthConfig webhookAuthConfig) {
        this.testCases = testCases;
        this.webhookAuthConfig = webhookAuthConfig;
    }

    /**
     * Generates the full content for {@code tests/dispatch_test.bal}.
     *
     * @return the generated Ballerina source string
     * @throws GeneratorException if the test cases are empty or the source fails to parse/format
     */
    public String generate() throws GeneratorException {
        if (testCases.isEmpty()) {
            throw new GeneratorException("No dispatch test cases to generate");
        }

        Map<String, List<DispatchTestCase>> byService = new LinkedHashMap<>();
        for (DispatchTestCase testCase : testCases) {
            byService.computeIfAbsent(testCase.serviceTypeName(), k -> new ArrayList<>()).add(testCase);
        }

        StringBuilder source = new StringBuilder();
        source.append(buildHeader());

        for (Map.Entry<String, List<DispatchTestCase>> entry : byService.entrySet()) {
            source.append(buildServiceStub(entry.getKey(), entry.getValue()));
        }

        source.append(buildSendHelper());
        source.append(buildWaitHelper());

        for (DispatchTestCase testCase : testCases) {
            source.append(buildTestFunction(testCase));
        }

        SyntaxTree syntaxTree = parse(source.toString());
        try {
            return Formatter.format(syntaxTree).toSourceCode();
        } catch (FormatterException e) {
            throw new GeneratorException("Could not format the generated dispatch_test.bal code", e);
        }
    }

    private SyntaxTree parse(String sourceText) {
        TextDocument textDocument = TextDocuments.from(sourceText);
        return SyntaxTree.from(textDocument);
    }

    private String buildHeader() {
        return "import ballerina/test;\n"
                + "import ballerina/http;\n"
                + "import ballerina/crypto;\n"
                + "import ballerina/io;\n"
                + "import ballerina/lang.runtime;\n\n"
                + "const string TRIGGER_TEST_SECRET = \"" + TEST_SECRET + "\";\n"
                + "const int TRIGGER_TEST_PORT = " + TEST_PORT + ";\n"
                + "const string TRIGGER_PAYLOAD_DIR = \"" + DEFAULT_PAYLOAD_DIR + "\";\n\n"
                + "map<boolean> triggerFired = {};\n\n"
                + "listener Listener triggerTestListener = "
                + "check new ({webhookSecret: TRIGGER_TEST_SECRET}, TRIGGER_TEST_PORT);\n\n";
    }

    private String buildServiceStub(String serviceTypeName, List<DispatchTestCase> functions) {
        StringBuilder sb = new StringBuilder();
        sb.append("service ").append(serviceTypeName).append(" on triggerTestListener {\n");
        for (DispatchTestCase testCase : functions) {
            sb.append("    remote function ").append(testCase.functionName())
                    .append("(").append(testCase.payloadTypeName()).append(" payload) returns error? {\n")
                    .append("        triggerFired[\"").append(serviceTypeName).append(".")
                    .append(testCase.functionName()).append("\"] = true;\n")
                    .append("    }\n");
        }
        sb.append("}\n\n");
        return sb.toString();
    }

    private String buildSendHelper() throws GeneratorException {
        String signatureHeader = webhookAuthConfig != null && webhookAuthConfig.headerName() != null
                ? webhookAuthConfig.headerName()
                : "X-Hub-Signature-256";
        String headerFormat = webhookAuthConfig != null ? webhookAuthConfig.headerFormat() : null;
        HeaderTemplate template = HeaderTemplateParser.parse(headerFormat);
        String signatureExpr = buildSignatureExpression(template);
        return "isolated function sendSignedTriggerWebhook(string headerValue, string eventIdentifier) "
                + "returns http:Response|error {\n"
                + "    byte[] body = check io:fileReadBytes(string `${TRIGGER_PAYLOAD_DIR}/${eventIdentifier}.json`);\n"
                + "    byte[] digest = check crypto:hmacSha256(body, TRIGGER_TEST_SECRET.toBytes());\n"
                + "    string computedSignature = digest.toBase16();\n"
                + "    string signature = " + signatureExpr + ";\n\n"
                + "    http:Client triggerClient = check new (string `http://localhost:${TRIGGER_TEST_PORT}`);\n"
                + "    http:Request request = new;\n"
                + "    request.setBinaryPayload(body, contentType = \"application/json\");\n"
                + "    request.setHeader(\"X-GitHub-Event\", headerValue);\n"
                + "    request.setHeader(\"" + signatureHeader + "\", signature);\n"
                + "    return triggerClient->post(\"/\", request);\n"
                + "}\n\n";
    }

    /**
     * Builds a Ballerina string-template expression that splices the computed signature into the
     * configured {@code headerFormat}, e.g. {@code headerFormat = "sha256=$signature"} becomes
     * {@code string `sha256=${computedSignature}`}. Only the {@code signature} placeholder is
     * substituted -- see the class-level doc for the scope of {@code headerFormat}s supported.
     *
     * @param template the parsed {@code headerFormat}
     * @return a Ballerina expression, as source text, evaluating to the full header value
     */
    private String buildSignatureExpression(HeaderTemplate template) {
        StringBuilder expression = new StringBuilder("string `");
        for (int i = 0; i < template.variables().size(); i++) {
            expression.append(escapeBacktickTemplate(template.literals().get(i)));
            String variable = template.variables().get(i);
            expression.append("${").append("signature".equals(variable) ? "computedSignature" : variable)
                    .append("}");
        }
        expression.append(escapeBacktickTemplate(template.literals().get(template.literals().size() - 1)));
        expression.append("`");
        return expression.toString();
    }

    private String escapeBacktickTemplate(String value) {
        return value.replace("\\", "\\\\").replace("`", "\\`");
    }

    private String buildTestFunction(DispatchTestCase testCase) {
        String testFnName = "test" + capitalize(testCase.functionName().replaceFirst("^on", "")) + "Dispatch";
        String trackerKey = testCase.serviceTypeName() + "." + testCase.functionName();
        return "@test:Config {}\n"
                + "function " + testFnName + "() returns error? {\n"
                + "    http:Response response = check sendSignedTriggerWebhook(\""
                + testCase.headerValue() + "\", \"" + testCase.eventIdentifier() + "\");\n"
                + "    test:assertEquals(response.statusCode, http:STATUS_OK);\n"
                + "    test:assertTrue(waitForDispatch(\"" + trackerKey + "\"), \""
                + trackerKey + " should have fired\");\n"
                + "}\n\n";
    }

    /**
     * Emits the {@code waitForDispatch} helper: the dispatcher acks before invoking the user's
     * handler, so the HTTP response the test client receives does not guarantee the handler has
     * finished running yet on the server side. Polls {@code triggerFired} briefly instead of
     * checking it once immediately after the response returns.
     */
    private String buildWaitHelper() {
        return "function waitForDispatch(string trackerKey) returns boolean {\n"
                + "    foreach int i in 0 ..< 20 {\n"
                + "        if triggerFired[trackerKey] ?: false {\n"
                + "            return true;\n"
                + "        }\n"
                + "        runtime:sleep(0.05);\n"
                + "    }\n"
                + "    return false;\n"
                + "}\n\n";
    }

    private String capitalize(String value) {
        if (value.isEmpty()) {
            return value;
        }
        return Character.toUpperCase(value.charAt(0)) + value.substring(1);
    }
}
