/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package io.ballerina.asyncapi.generator.http.generator;

import io.ballerina.asyncapi.generator.GeneratorException;
import io.ballerina.asyncapi.generator.http.extractor.EventIdentifierExtractor;
import io.ballerina.asyncapi.generator.http.model.DispatchTestCase;
import io.ballerina.asyncapi.generator.http.model.EventIdentifierConfig;
import io.ballerina.asyncapi.generator.http.model.WebhookAuthConfig;
import io.ballerina.asyncapi.generator.http.utils.HeaderTemplateParser;
import io.ballerina.asyncapi.generator.http.utils.HeaderTemplateParser.HeaderTemplate;
import io.ballerina.asyncapi.generator.http.utils.SignaturePayloadTemplateBuilder;
import io.ballerina.asyncapi.generator.http.utils.WebhookCryptoMapper;
import io.ballerina.compiler.syntax.tree.SyntaxTree;
import io.ballerina.tools.text.TextDocument;
import io.ballerina.tools.text.TextDocuments;
import org.ballerinalang.formatter.core.Formatter;
import org.ballerinalang.formatter.core.FormatterException;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates {@code tests/dispatch_test.bal}: one real {@code @test:Config} dispatch-verification
 * test per event defined in the spec, plus one stub service implementation per service type
 * covering every one of its remote functions.
 *
 * <p>Each test sends a signed HTTP request built from a same-named JSON fixture (expected at
 * {@code <payloadDir>/<eventIdentifier>.json}, not generated by this class -- fixtures are
 * curated data, not synthesizable from a schema alone) to a listener started on a dedicated test
 * port, then asserts the expected remote function fired. The fixture's raw bytes are sent (and
 * signed) as-is, so for a spec with {@code x-ballerina-event-identifier.batched: true} the fixture
 * itself must be authored as a one-element JSON array (e.g. {@code [{...}]}), not a bare object --
 * this class has no batching awareness of its own, since it only forwards whatever shape the
 * fixture already is.
 *
 * <p>Signing mirrors {@link io.ballerina.asyncapi.generator.http.node.GenerateVerifyWebhookSignatureFuncNode}'s
 * server-side verification, driven by the same {@code x-ballerina-auth} DSL: any algorithm/encoding
 * combination, both {@code hmac} and {@code hash} strategies, {@code $config(...)}-derived values
 * (threaded into the test listener's configuration), and a freshness-check header (synthesized as
 * the current timestamp). The event-identifier header is only set for {@code header}/{@code composite}
 * identifier modes; {@code body}-mode identifiers are expected to already be present in the fixture.
 */
public class DispatchTestGenerator {

    private static final String DEFAULT_PAYLOAD_DIR = "tests/resources/trigger_payloads";
    private static final int TEST_PORT = 9091;
    private static final String TEST_SECRET = "trigger-test-secret";
    private static final String DEFAULT_IDENTIFIER_HEADER = "X-GitHub-Event";

    private final List<DispatchTestCase> testCases;
    private final WebhookAuthConfig webhookAuthConfig;
    private final EventIdentifierConfig identifierConfig;

    /**
     * Creates a generator for the given dispatch test cases, webhook authentication configuration,
     * and event-identifier configuration.
     *
     * @param testCases         the extracted dispatch test cases, one per event
     * @param webhookAuthConfig the webhook authentication configuration (header name, algorithm)
     * @param identifierConfig  the resolved event identifier type, header name, and body path
     */
    public DispatchTestGenerator(List<DispatchTestCase> testCases, WebhookAuthConfig webhookAuthConfig,
            EventIdentifierConfig identifierConfig) {
        this.testCases = testCases;
        this.webhookAuthConfig = webhookAuthConfig;
        this.identifierConfig = identifierConfig;
    }

    /**
     * Generates the full content for {@code tests/dispatch_test.bal}.
     *
     * @return the generated Ballerina source string
     * @throws GeneratorException if the test cases are empty or the source fails to parse/format
     */
    public String generate() throws GeneratorException {
        if (testCases.isEmpty()) {
            throw new GeneratorException("No dispatch test cases to generate");
        }

        Map<String, List<DispatchTestCase>> byService = new LinkedHashMap<>();
        for (DispatchTestCase testCase : testCases) {
            byService.computeIfAbsent(testCase.serviceTypeName(), k -> new ArrayList<>()).add(testCase);
        }

        List<String> headerRefs = webhookAuthConfig != null && webhookAuthConfig.input() != null
                ? SignaturePayloadTemplateBuilder.extractHeaderReferences(webhookAuthConfig.input())
                : List.of();

        StringBuilder source = new StringBuilder();
        source.append(buildHeader(headerRefs));

        for (Map.Entry<String, List<DispatchTestCase>> entry : byService.entrySet()) {
            source.append(buildServiceStub(entry.getKey(), entry.getValue()));
        }

        source.append(buildSendHelper(headerRefs));
        source.append(buildWaitHelper());

        for (DispatchTestCase testCase : testCases) {
            source.append(buildTestFunction(testCase));
        }

        SyntaxTree syntaxTree = parse(source.toString());
        try {
            return Formatter.format(syntaxTree).toSourceCode();
        } catch (FormatterException e) {
            throw new GeneratorException("Could not format the generated dispatch_test.bal code", e);
        }
    }

    private SyntaxTree parse(String sourceText) {
        TextDocument textDocument = TextDocuments.from(sourceText);
        return SyntaxTree.from(textDocument);
    }

    private String buildHeader(List<String> headerRefs) {
        StringBuilder imports = new StringBuilder()
                .append("import ballerina/test;\n")
                .append("import ballerina/http;\n")
                .append("import ballerina/crypto;\n")
                .append("import ballerina/io;\n")
                .append("import ballerina/lang.runtime;\n");
        if (needsTimeImport(headerRefs)) {
            imports.append("import ballerina/time;\n");
        }

        StringBuilder constants = new StringBuilder()
                .append("const TRIGGER_TEST_SECRET = \"").append(TEST_SECRET).append("\";\n")
                .append("const TRIGGER_TEST_PORT = ").append(TEST_PORT).append(";\n")
                .append("const TRIGGER_PAYLOAD_DIR = \"").append(DEFAULT_PAYLOAD_DIR).append("\";\n");

        StringBuilder listenerConfigFields = new StringBuilder("webhookSecret: TRIGGER_TEST_SECRET");
        if (webhookAuthConfig != null && webhookAuthConfig.configFields() != null) {
            for (String field : webhookAuthConfig.configFields()) {
                String constName = testConfigConstantName(field);
                constants.append("const ").append(constName).append(" = \"test-")
                        .append(field).append("-value\";\n");
                listenerConfigFields.append(", ").append(field).append(": ").append(constName);
            }
        }

        return imports.toString() + "\n" + constants
                + "\nisolated map<boolean> triggerFired = {};\n\n"
                + "listener Listener triggerTestListener = "
                + "check new ({" + listenerConfigFields + "}, TRIGGER_TEST_PORT);\n\n"
                + "final http:Client triggerClient = "
                + "check new (string `http://localhost:${TRIGGER_TEST_PORT}`);\n\n";
    }

    private boolean needsTimeImport(List<String> headerRefs) {
        String freshnessHeader = webhookAuthConfig != null ? webhookAuthConfig.freshnessHeader() : null;
        return freshnessHeader != null && headerRefs.contains(freshnessHeader);
    }

    private String buildServiceStub(String serviceTypeName, List<DispatchTestCase> functions) {
        StringBuilder sb = new StringBuilder();
        sb.append("service ").append(serviceTypeName).append(" on triggerTestListener {\n");
        for (DispatchTestCase testCase : functions) {
            sb.append("    isolated remote function ").append(testCase.functionName())
                    .append("(").append(testCase.payloadTypeName()).append(" payload) returns error? {\n")
                    .append("        lock {\n")
                    .append("            triggerFired[\"").append(serviceTypeName).append(".")
                    .append(testCase.functionName()).append("\"] = true;\n")
                    .append("        }\n")
                    .append("    }\n");
        }
        sb.append("}\n\n");
        return sb.toString();
    }

    private String buildSendHelper(List<String> headerRefs) throws GeneratorException {
        StringBuilder sb = new StringBuilder();
        sb.append("isolated function sendSignedTriggerWebhook(string headerValue, string eventIdentifier) "
                + "returns http:Response|error {\n");
        sb.append("    byte[] body = check io:fileReadBytes("
                + "string `${TRIGGER_PAYLOAD_DIR}/${eventIdentifier}.json`);\n");
        sb.append("    string bodyText = check string:fromBytes(body);\n");

        List<String> headerEntries = new ArrayList<>();

        String identifierType = identifierConfig != null ? identifierConfig.type() : null;
        if (!EventIdentifierExtractor.X_BALLERINA_EVENT_TYPE_BODY.equals(identifierType)) {
            String identifierHeaderName = identifierConfig != null && identifierConfig.name() != null
                    ? identifierConfig.name()
                    : DEFAULT_IDENTIFIER_HEADER;
            headerEntries.add("\"" + identifierHeaderName + "\": headerValue");
        }

        String freshnessHeader = webhookAuthConfig != null ? webhookAuthConfig.freshnessHeader() : null;
        Map<String, String> headerVarNames = new LinkedHashMap<>();
        for (String headerRef : headerRefs) {
            String varName = headerVarName(headerRef);
            headerVarNames.put(headerRef, varName);
            if (freshnessHeader != null && freshnessHeader.equals(headerRef)) {
                // A real timestamp -- this header may also be validated by a freshness check, which
                // requires a numeric, currently-fresh value, not just an arbitrary test string.
                sb.append("    string ").append(varName).append(" = (time:utcNow()[0] * 1000).toString();\n");
            } else {
                // Client and server only need to agree on *some* value for this header -- what the
                // test sends is what verification reads back, so any string is a valid signed input.
                sb.append("    string ").append(varName).append(" = \"test-header-value\";\n");
            }
            headerEntries.add("\"" + headerRef + "\": " + varName);
        }

        String inputDsl = webhookAuthConfig != null && webhookAuthConfig.input() != null
                ? webhookAuthConfig.input()
                : "$body";
        String balTemplate = SignaturePayloadTemplateBuilder.build(
                escapeBacktickTemplate(inputDsl), clientTokenResolver(headerVarNames));
        sb.append("    string payloadToHash = string `").append(balTemplate).append("`;\n");

        String signatureHeader = webhookAuthConfig != null && webhookAuthConfig.headerName() != null
                ? webhookAuthConfig.headerName()
                : "X-Hub-Signature-256";
        String headerFormat = webhookAuthConfig != null ? webhookAuthConfig.headerFormat() : null;
        HeaderTemplate template = HeaderTemplateParser.parse(headerFormat);

        String algorithm = webhookAuthConfig != null ? webhookAuthConfig.algorithm() : null;
        String signatureVariable;
        if (algorithm != null && !algorithm.isBlank()) {
            boolean isPlainHash = webhookAuthConfig != null && "hash".equalsIgnoreCase(webhookAuthConfig.strategy());
            if (isPlainHash) {
                String cryptoFunc = WebhookCryptoMapper.hashFunctionFor(algorithm);
                sb.append("    byte[] computedDigest = crypto:").append(cryptoFunc)
                        .append("(payloadToHash.toBytes());\n");
            } else {
                String cryptoFunc = WebhookCryptoMapper.hmacFunctionFor(algorithm);
                sb.append("    byte[] computedDigest = check crypto:").append(cryptoFunc)
                        .append("(payloadToHash.toBytes(), TRIGGER_TEST_SECRET.toBytes());\n");
            }
            String encoding = webhookAuthConfig.encoding() != null ? webhookAuthConfig.encoding() : "hex";
            String encodeFunc = WebhookCryptoMapper.encodeFunctionFor(encoding);
            sb.append("    string computedSignature = computedDigest.").append(encodeFunc).append(";\n");
            signatureVariable = "computedSignature";
        } else {
            // Static token mode: the header carries the secret itself, compared directly server-side.
            signatureVariable = "TRIGGER_TEST_SECRET";
        }

        String signatureExpr = buildSignatureExpression(template, signatureVariable);
        headerEntries.add("\"" + signatureHeader + "\": " + signatureExpr);

        sb.append("    map<string> headers = {\n");
        for (int i = 0; i < headerEntries.size(); i++) {
            sb.append("        ").append(headerEntries.get(i));
            sb.append(i < headerEntries.size() - 1 ? ",\n" : "\n");
        }
        sb.append("    };\n");
        sb.append("    return triggerClient->post(\"/\", body, headers, \"application/json\");\n");
        sb.append("}\n\n");
        return sb.toString();
    }

    private SignaturePayloadTemplateBuilder.TokenResolver clientTokenResolver(Map<String, String> headerVarNames) {
        return new SignaturePayloadTemplateBuilder.TokenResolver() {
            @Override
            public String body() {
                return "bodyText";
            }

            @Override
            public String uri() {
                return "\"/\"";
            }

            @Override
            public String method() {
                return "\"POST\"";
            }

            @Override
            public String secret() {
                return "TRIGGER_TEST_SECRET";
            }

            @Override
            public String header(String headerName) {
                return headerVarNames.get(headerName);
            }

            @Override
            public String config(String configName) {
                return testConfigConstantName(configName);
            }
        };
    }

    /**
     * Derives a Ballerina-safe local variable name for the synthesized value of a referenced header,
     * e.g. {@code "X-HubSpot-Request-Timestamp"} becomes {@code "xHubSpotRequestTimestampHeaderValue"}.
     */
    private String headerVarName(String headerName) {
        StringBuilder camel = new StringBuilder();
        boolean capitalizeNext = false;
        for (char c : headerName.toCharArray()) {
            if (!Character.isLetterOrDigit(c)) {
                capitalizeNext = true;
                continue;
            }
            camel.append(capitalizeNext && !camel.isEmpty() ? Character.toUpperCase(c) : Character.toLowerCase(c));
            capitalizeNext = false;
        }
        return camel + "HeaderValue";
    }

    /**
     * Builds a Ballerina string-template expression that splices the resolved signature value into
     * the configured {@code headerFormat}, e.g. {@code headerFormat = "sha256=$signature"} with
     * {@code signatureVariable = "computedSignature"} becomes {@code string `sha256=${computedSignature}`}.
     * Only the {@code signature} placeholder is substituted -- see the class-level doc for the scope
     * of {@code headerFormat}s supported.
     *
     * @param template          the parsed {@code headerFormat}
     * @param signatureVariable the Ballerina variable name holding the resolved signature value
     * @return a Ballerina expression, as source text, evaluating to the full header value
     */
    private String buildSignatureExpression(HeaderTemplate template, String signatureVariable) {
        StringBuilder expression = new StringBuilder("string `");
        for (int i = 0; i < template.variables().size(); i++) {
            expression.append(escapeBacktickTemplate(template.literals().get(i)));
            String variable = template.variables().get(i);
            expression.append("${").append("signature".equals(variable) ? signatureVariable : variable)
                    .append("}");
        }
        expression.append(escapeBacktickTemplate(template.literals().get(template.literals().size() - 1)));
        expression.append("`");
        return expression.toString();
    }

    private String escapeBacktickTemplate(String value) {
        return value.replace("\\", "\\\\").replace("`", "\\`");
    }

    private String testConfigConstantName(String configFieldName) {
        StringBuilder upperSnake = new StringBuilder();
        for (int i = 0; i < configFieldName.length(); i++) {
            char c = configFieldName.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                upperSnake.append('_');
            }
            upperSnake.append(Character.toUpperCase(c));
        }
        return "TRIGGER_TEST_" + upperSnake;
    }

    private String buildTestFunction(DispatchTestCase testCase) {
        String testFnName = "test" + capitalize(testCase.functionName().replaceFirst("^on", "")) + "Dispatch";
        String trackerKey = testCase.serviceTypeName() + "." + testCase.functionName();
        return "@test:Config {}\n"
                + "function " + testFnName + "() returns error? {\n"
                + "    http:Response response = check sendSignedTriggerWebhook(\""
                + testCase.headerValue() + "\", \"" + testCase.eventIdentifier() + "\");\n"
                + "    test:assertEquals(response.statusCode, http:STATUS_OK);\n"
                + "    test:assertTrue(waitForDispatch(\"" + trackerKey + "\"), \""
                + trackerKey + " should have fired\");\n"
                + "}\n\n";
    }

    /**
     * Emits the {@code waitForDispatch} helper: the dispatcher acks before invoking the user's
     * handler, so the HTTP response the test client receives does not guarantee the handler has
     * finished running yet on the server side. Polls {@code triggerFired} briefly instead of
     * checking it once immediately after the response returns.
     */
    private String buildWaitHelper() {
        return "function waitForDispatch(string trackerKey) returns boolean {\n"
                + "    foreach int i in 0 ..< 20 {\n"
                + "        lock {\n"
                + "            if triggerFired[trackerKey] ?: false {\n"
                + "                return true;\n"
                + "            }\n"
                + "        }\n"
                + "        runtime:sleep(0.05);\n"
                + "    }\n"
                + "    return false;\n"
                + "}\n\n";
    }

    private String capitalize(String value) {
        if (value.isEmpty()) {
            return value;
        }
        return Character.toUpperCase(value.charAt(0)) + value.substring(1);
    }
}
