/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'java'
    id 'checkstyle'
    id 'com.github.johnrengelman.shadow'
}

description = "Ballerina - AsyncAPI Generator"

dependencies {
    checkstyle project(':checkstyle')
    checkstyle "com.puppycrawl.tools:checkstyle:${checkstylePluginVersion}"

    implementation project(':asyncapi-core')
    implementation "io.apicurio:apicurio-data-models:2.3.1"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonDataformatYamlVersion}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonDataformatYamlVersion}"
    implementation "commons-io:commons-io:${commonsIoVersion}"
    compileOnly "org.ballerinalang:ballerina-parser:${ballerinaLangVersion}"
    compileOnly "org.ballerinalang:formatter-core:${ballerinaLangVersion}"
    compileOnly "org.ballerinalang:ballerina-tools-api:${ballerinaLangVersion}"
    compileOnly "org.ballerinalang:ballerina-runtime:${ballerinaLangVersion}"
    implementation "org.semver4j:semver4j:${semver4jVersion}"
    runtimeOnly "org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"
}

checkstyle {
    toolVersion "${checkstylePluginVersion}"
    configFile rootProject.file("config/checkstyle/build/checkstyle.xml")
    configProperties = ["suppressionFile": file("${rootDir}/config/checkstyle/build/suppressions.xml")]
}

def excludePattern = '**/module-info.java'
tasks.withType(Checkstyle) {
    exclude excludePattern
}

test {
    useTestNG() {
        suites "src/test/resources/testng.xml"
    }
    jvmArgs '-Dlog4j2.level=INFO'
}

checkstyleMain.dependsOn(":checkstyle:build")
checkstyleTest.dependsOn(":checkstyle:build")

jar {
    enabled = false
    dependsOn(shadowJar { archiveClassifier = null })
}

shadowJar {
    configurations = [project.configurations.runtimeClasspath]
    dependencies {
        include(dependency("commons-io:commons-io:${commonsIoVersion}"))
        include(dependency("org.apache.logging.log4j:log4j-slf4j-impl:${log4jVersion}"))
        include(dependency("org.apache.logging.log4j:log4j-api:${log4jVersion}"))
        exclude('META-INF/*.SF')
        exclude('META-INF/*.DSA')
        exclude('META-INF/*.RSA')
    }
    exclude 'org/slf4j/impl/StaticLoggerBinder.class'
    exclude 'org/slf4j/impl/StaticMDCBinder.class'
    exclude 'org/slf4j/impl/StaticMarkerBinder.class'
}

